disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ney"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006"
  logo = "img/second-logo.png"
  secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Thiago Rodrigues"
  email = "thiagoneye@outlook.com"
  image = "img/photo.png"
  imageQuality = 100
  headline = "Computational Engineering | Fluid Dynamics | Data Science | SciML"
  bio = "Computational Engineering | Fluid Dynamics | Data Science | SciML"
  links = [
    { email = "mailto:thiagoneye@outlook.com" },
    { github = "https://github.com/thiagoneye" },
    { linkedin = "https://linkedin.com/in/thiagoney" },
    { researchgate = "https://www.researchgate.net/profile/Thiago_Rodrigues16" },
    { orcid = "https://orcid.org/0000-0002-0100-608X" },
    { google = "https://scholar.google.com/citations?user=gIVRWqsAAAAJ&hl" },
  ]