baseURL: https://thiagoneye.github.io/
languageCode: en-us
title: Home
theme: PaperMod
publishDir: docs

menu:
  main:
    - name: "About Me"
      url: about_me/
      weight: 2
    - name: Experience
      url: experience/
      weight: 3
    - name: Research
      url: research/
      weight: 4
    - name: Publications
      url: publications/
      weight: 5
    - name: Others
      url: others/
      weight: 6
    - name: Tags
      url: tags/
      weight: 7
    - name: Contact
      url: contact/
      weight: 8

params:
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: true
  profileMode:
    enabled: true
    title: "Thiago Rodrigues" # optional default will be site title
    subtitle: "Bachelor's degree in Mechanical Engineering from UFPB, currently pursuing a Specialization in Data Engineering at PUC Minas and a Master's in Computer Science at UFPB. Conduct research at TRIL Lab, focusing on applying Data-Driven Techniques and Scientific Machine Learning approaches to model and solve engineering problems. Enthusiastic about scientific and technological development, he aims to develop projects for the benefit of humanity."
    imageUrl: "/picture.jpeg" # optional
    imageTitle: "Profile Picture" # optional
    imageWidth: 160 # custom size
    imageHeight: 160 # custom size
#    buttons:
#      - name: "About Me"
#        url: about_me/
#      - name: Experience
#        url: experience/
#      - name: Research
#        url: research/
#      - name: Publications
#        url: publications/
#      - name: Others
#        url: others/
#      - name: Contact
#        url: contact/
  socialIcons: # optional
    - name: Email
      url: mailto:thiagoneye@outlook.com
    - name: Location
      url: contact/
    - name: GitHub
      url: https://github.com/thiagoneye
    - name: LinkedIn
      url: https://www.linkedin.com/in/thiagoney
    - name: ResearchGate
      url: https://www.researchgate.net/profile/Thiago_Rodrigues16
    - name: ORCID
      url: https://orcid.org/0000-0002-0100-608X
